//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class FCT : IEquatable<FCT>
    {
        public FCT()
        {
        }

        public FCT(Alumno alumno)
        {
            Alumno = alumno;
        }

        public FCT(int nMatricula, int idEmpresa, string tutorInsti, string tutorEmpresa, Alumno alumno, Empresa empresa, Profe profe)
        {
            NMatricula = nMatricula;
            IdEmpresa = idEmpresa;
            TutorInsti = tutorInsti;
            TutorEmpresa = tutorEmpresa;
            Alumno = alumno;
            Empresa = empresa;
            Profe = profe;
        }

        public int NMatricula { get; set; }
        public int IdEmpresa { get; set; }
        public string TutorInsti { get; set; }
        public string TutorEmpresa { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Profe Profe { get; set; }

        public override bool Equals(object obj)
        {
            return Equals(obj as FCT);
        }

        public bool Equals(FCT other)
        {
            return other != null &&
                   NMatricula == other.NMatricula;
        }

        public override int GetHashCode()
        {
            return 1687765875 + NMatricula.GetHashCode();
        }
    }
}
