//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using Entidades;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BdFCTsEntities : DbContext
    {
        public BdFCTsEntities()
            : base("name=BdFCTsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> Alumnos { get; set; }
        public virtual DbSet<Ciclo> Ciclos { get; set; }
        public virtual DbSet<Empresa> Empresas { get; set; }
        public virtual DbSet<FCT> FCTs { get; set; }
        public virtual DbSet<OfertasFCT> OfertasFCTs { get; set; }
        public virtual DbSet<Profe> Profes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
